### PR TITLE
Data preprocessing Python script added

### PR DESCRIPTION
**Pull request by LoicVerrall**
Feel free to **not** merge this yet. I just wanted you to see my code as it's coming along.

### CODE REVIEW

**Review by danarth — CHANGES_REQUESTED** [review]
Please change the name of the directory to be unix-friendly:
- No caps
- No spaces

Maybe to something like `preprocessing`? Also, do we need to commit both the `old_process.py` and the `process_postcodes.py`?

**Comment by LoicVerrall** [comment]
Sure. We don't really need the old one, but I thought it would be good to have a version of it somewhere here. How about if I remove it in a new commit, so there is some record of it (in this commit)?

**Comment by danarth** [comment]
It's your call, it can stay if you think it should. I am not sure if we aren't using it for the preprocessing we even need it in commit history? Like obviously keep it locally but do we need it do ou think?

Sorry for being picky, like I say if you think it should stay we'll keep it 😄

**Comment by LoicVerrall** [comment]
Yeah, that makes sense — I'll leave it out.
Bit scared to muck around with the directory structure while it's running so I'll do it tomorrow 👍

**Comment by danarth** [comment]
That's not a problem 😄 I'll merge once you change it 👍

**Pull request closed without merging**
