### PR TITLE
Two demo tests added to test Travis configuration

### PR DESCRIPTION
**Pull request by LoicVerrall**

### CODE REVIEW

**Comment by danarth** [comment]
Looks like the test you wanted to fail, failed! 😀 Big up Travis CI :smile:

**Comment by LoicVerrall** [comment]
Wow, I'm seriously impressed. Thanks for setting this all up! 🙌

**Comment by LoicVerrall** [comment]
How is coveralls reporting 100% code coverage though...?

**Comment by danarth** [comment]
@LoicVerrall I'll look into it... it might be normal behaviour 😆

**Pull request merged**
